### ISSUE TITLE
CORS Error when trying to access the API

### ISSUE THREAD

**Issue by lcrossan** [dmuth/IsSeptaFcked#1]
Hey!

I'm trying to build an Ionic application that consumes your API, and I keep running into CORS problems when making a GET request to get some data.

Would you mind enabling cross-origin requests on whatever server hosts your API?

Thanks!

**Comment by dmuth** [comment]
Oh, uh... thanks for closing that automatically, GitHub. 🙀 

Anyway, you should have CORS headers when hitting any URI that starts with /api, as shown below:

```
$ curl -I www.isseptafucked.com/api
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Type: text/html; charset=utf-8
Content-Length: 6774
Date: Thu, 09 Feb 2017 02:49:47 GMT
Via: 1.1 vegur
```

Please let me know if you run into any issues.

Thanks,

-- Doug
